WITH substantial_data AS (
    SELECT *
    FROM (
        SELECT 
            *,
            LAG(BEGIN_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT) AS prev_beg,
            LAG(END_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT) AS prev_end
        FROM (
            SELECT
                INSURANCE_CONTRACT_ID,
                COALESCE(ENDORSEMENT_DT, DATE('1990-01-01')) AS ENDORSEMENT_DT,
                BEGIN_COV_DT,
                END_COV_DT
            FROM PSAKPROD.INS_CONTRACT_OBJECT_KBM_2016_2020
            WHERE INSURANCE_CONTRACT_ID IN (
                SELECT INSURANCE_CONTRACT_ID
                FROM (
                    SELECT
                        INSURANCE_CONTRACT_ID,
                        ENDORSEMENT_DT,
                        ROW_NUMBER() OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT) AS num
                    FROM PSAKPROD.INS_CONTRACT_OBJECT_KBM_2016_2020
                ) 
                WHERE num > 1
            )
			ORDER BY INSURANCE_CONTRACT_ID, ENDORSEMENT_DT
        ) AS inner_query
		ORDER BY INSURANCE_CONTRACT_ID, ENDORSEMENT_DT
    ) AS lagged_query
    WHERE BEGIN_COV_DT <> prev_beg OR END_COV_DT <> prev_end
    ORDER BY INSURANCE_CONTRACT_ID, ENDORSEMENT_DT
),
stg_object AS (
    SELECT 
        REPORTING_DT,
        ENTITY_ID,
        INSURANCE_CONTRACT_ID,
        '' AS ENDORSEMENT_TYPE_CD,
        ENDORSEMENT_DT,
        ISSUE_DT,
        ENDORSEMENT_DT AS BEGIN_COV_DT,
        END_COV_DT,
        PREM_AMT,
        PRODUCT_LINE_ID,
        PRODUCT_ID,
        COHORT_ID,
        CEDED_FLG,
        INSURANCE_TYPE,
        REINS_PROP_COVER_FLG,
        REINS_TREATY_FLG,
        INTERCO_CD,
        INTERCO_FLG,
        BRANCH_CD,
        CHANNEL_CD,
        APPROACH_CD,
        TRANSITION_APPROACH_CD,
        TRANSITION_REPORTING_APPROACH_CD,
        CURRENCY_CD,
        COMMISSION_AMT,
        PD,
        LGD,
        PROFITABILITY,
        LOAD_TIME,
        TRANSITION_REL_RA_PAST_PER_AMT,
        TRANSITION_CUMULATIVE_OCI_AMT,
        TRANSITION_CSM_PAST_UNWIND_AMT,
        TRANSITION_INPUT_CSM_AMT,
        TRANSITION_INPUT_LC_BE_AMT,
        TRANSITION_INPUT_LC_RA_AMT,
        TRANSITION_LC_BE_PAST_UNWIND_AMT,
        TRANSITION_LC_RA_PAST_UNWIND_AMT,
        FIELD_SOURCE,
        1 AS IS_SUBSTANTIAL,
        ENDORSEMENT_DT AS BEGIN_COV_DT_I,
        END_COV_DT AS END_COV_DT_I,
        PREM_AMT_N,
        IS_CHN_COV,
        ENDORSEMENT_DT AS BEGIN_COV_DT_N,
        CASE 
            WHEN ENDORSEMENT_DT < END_COV_DT THEN END_COV_DT 
            ELSE LAST_DAY(ENDORSEMENT_DT)
        END AS END_COV_DT_N
    FROM (
        SELECT *,
            CASE 
                WHEN END_COV_DT != LAG(END_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                OR BEGIN_COV_DT != LAG(BEGIN_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                THEN SUM(PREM_AMT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT) 
                ELSE PREM_AMT 
            END AS PREM_AMT_N,
            CASE 
                WHEN END_COV_DT != LAG(END_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                OR BEGIN_COV_DT != LAG(BEGIN_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                THEN 1 
                ELSE 0 
            END AS IS_CHN_COV
        FROM (
            SELECT
                REPORTING_DT,
                ENTITY_ID,
                INSURANCE_CONTRACT_ID,
                ENDORSEMENT_TYPE_CD,
                COALESCE(ENDORSEMENT_DT, DATE('1990-01-01')) AS ENDORSEMENT_DT,
                ISSUE_DT,
                BEGIN_COV_DT,
                END_COV_DT,
                PREM_AMT,
                PRODUCT_LINE_ID,
                PRODUCT_ID,
                COHORT_ID,
                CEDED_FLG,
                INSURANCE_TYPE,
                REINS_PROP_COVER_FLG,
                REINS_TREATY_FLG,
                INTERCO_CD,
                INTERCO_FLG,
                BRANCH_CD,
                CHANNEL_CD,
                APPROACH_CD,
                TRANSITION_APPROACH_CD,
                TRANSITION_REPORTING_APPROACH_CD,
                CURRENCY_CD,
                COMMISSION_AMT,
                PD,
                LGD,
                PROFITABILITY,
                LOAD_TIME,
                TRANSITION_REL_RA_PAST_PER_AMT,
                TRANSITION_CUMULATIVE_OCI_AMT,
                TRANSITION_CSM_PAST_UNWIND_AMT,
                TRANSITION_INPUT_CSM_AMT,
                TRANSITION_INPUT_LC_BE_AMT,
                TRANSITION_INPUT_LC_RA_AMT,
                TRANSITION_LC_BE_PAST_UNWIND_AMT,
                TRANSITION_LC_RA_PAST_UNWIND_AMT,
                FIELD_SOURCE
            FROM PSAKPROD.INS_CONTRACT_OBJECT_KBM_2016_2020
            WHERE INSURANCE_CONTRACT_ID IN (SELECT INSURANCE_CONTRACT_ID FROM substantial_data)
            AND INSURANCE_CONTRACT_ID = '526-605-200-16-00047-000'
			ORDER BY INSURANCE_CONTRACT_ID, ENDORSEMENT_DT
        ) AS main_query
        ORDER BY INSURANCE_CONTRACT_ID, ENDORSEMENT_DT
    ) AS result_query
    WHERE IS_CHN_COV = 1
    UNION ALL
    SELECT *,
        CASE 
            WHEN END_COV_DT != LAG(END_COV_DT, 1) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
            OR BEGIN_COV_DT != LAG(BEGIN_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
            THEN LAG(BEGIN_COV_DT_I, 1) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
            ELSE MAX(BEGIN_COV_DT_I) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT) 
        END AS BEGIN_COV_DT_N,
        END_COV_DT_I AS END_COV_DT_N
    FROM (
        SELECT *,
            CASE 
                WHEN END_COV_DT != LAG(END_COV_DT, 1) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                OR BEGIN_COV_DT != LAG(BEGIN_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                THEN ENDORSEMENT_DT 
                ELSE BEGIN_COV_DT 
            END AS BEGIN_COV_DT_I,
            CASE 
                WHEN END_COV_DT != LAG(END_COV_DT, 1) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                OR BEGIN_COV_DT != LAG(BEGIN_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                THEN COALESCE(LAG(END_COV_DT, 1) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT), END_COV_DT) 
                ELSE END_COV_DT 
            END AS END_COV_DT_I,  
            CASE 
                WHEN END_COV_DT != LAG(END_COV_DT, 1) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                OR BEGIN_COV_DT != LAG(BEGIN_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                THEN -1 * (SUM(PREM_AMT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT) - PREM_AMT) 
                ELSE PREM_AMT 
            END AS PREM_AMT_N,
            CASE 
                WHEN END_COV_DT != LAG(END_COV_DT, 1) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                OR BEGIN_COV_DT != LAG(BEGIN_COV_DT) OVER (PARTITION BY INSURANCE_CONTRACT_ID ORDER BY ENDORSEMENT_DT,BEGIN_COV_DT,END_COV_DT)
                THEN 1 
                ELSE 0 
            END AS IS_CHN_COV
        FROM (
            SELECT
                REPORTING_DT,
                ENTITY_ID,
                INSURANCE_CONTRACT_ID,
                ENDORSEMENT_TYPE_CD,
                COALESCE(ENDORSEMENT_DT, DATE('1990-01-01')) AS ENDORSEMENT_DT,
                ISSUE_DT,
                BEGIN_COV_DT,
                END_COV_DT,
                PREM_AMT,
                PRODUCT_LINE_ID,
                PRODUCT_ID,
                COHORT_ID,
                CEDED_FLG,
                INSURANCE_TYPE,
                REINS_PROP_COVER_FLG,
                REINS_TREATY_FLG,
                INTERCO_CD,
                INTERCO_FLG,
                BRANCH_CD,
                CHANNEL_CD,
                APPROACH_CD,
                TRANSITION_APPROACH_CD,
                TRANSITION_REPORTING_APPROACH_CD,
                CURRENCY_CD,
                COMMISSION_AMT,
                PD,
                LGD,
                PROFITABILITY,
                LOAD_TIME,
                TRANSITION_REL_RA_PAST_PER_AMT,
                TRANSITION_CUMULATIVE_OCI_AMT,
                TRANSITION_CSM_PAST_UNWIND_AMT,
                TRANSITION_INPUT_CSM_AMT,
                TRANSITION_INPUT_LC_BE_AMT,
                TRANSITION_INPUT_LC_RA_AMT,
                TRANSITION_LC_BE_PAST_UNWIND_AMT,
                TRANSITION_LC_RA_PAST_UNWIND_AMT,
                FIELD_SOURCE,
                0 AS IS_SUBSTANTIAL
            FROM PSAKPROD.INS_CONTRACT_OBJECT_KBM_2016_2020
            WHERE INSURANCE_CONTRACT_ID IN (SELECT INSURANCE_CONTRACT_ID FROM substantial_data)
            AND INSURANCE_CONTRACT_ID = '526-605-200-16-00047-000'
			ORDER BY INSURANCE_CONTRACT_ID, ENDORSEMENT_DT
        ) AS main_query
        ORDER BY INSURANCE_CONTRACT_ID, ENDORSEMENT_DT, IS_SUBSTANTIAL
    ) AS result_query
    ORDER BY INSURANCE_CONTRACT_ID, ENDORSEMENT_DT, IS_SUBSTANTIAL
)
SELECT
    REPORTING_DT,
    ENTITY_ID,
    INSURANCE_CONTRACT_ID,
    ENDORSEMENT_TYPE_CD,
    ENDORSEMENT_DT,
    ISSUE_DT,
    BEGIN_COV_DT_N AS BEGIN_COV_DT,
    END_COV_DT_N AS END_COV_DT,
    PREM_AMT,
    CAST(PREM_AMT_N AS DECIMAL(30,5)) AS PREM_AMT_N,
    DAYS(END_COV_DT_N) - DAYS(BEGIN_COV_DT_N) AS POT_1,
    CASE 
        WHEN ENDORSEMENT_TYPE_CD = '' OR ENDORSEMENT_DT = DATE('1990-01-01') THEN NULL 
        ELSE DAYS(END_COV_DT_N) - DAYS(ENDORSEMENT_DT) 
    END AS POT_2,
    PRODUCT_LINE_ID,
    PRODUCT_ID,
    COHORT_ID,
    CEDED_FLG,
    INSURANCE_TYPE,
    REINS_PROP_COVER_FLG,
    REINS_TREATY_FLG,
    INTERCO_CD,
    INTERCO_FLG,
    BRANCH_CD,
    CHANNEL_CD,
    APPROACH_CD,
    TRANSITION_APPROACH_CD,
    TRANSITION_REPORTING_APPROACH_CD,
    CURRENCY_CD,
    COMMISSION_AMT,
    PD,
    LGD,
    PROFITABILITY,
    LOAD_TIME,
    TRANSITION_REL_RA_PAST_PER_AMT,
    TRANSITION_CUMULATIVE_OCI_AMT,
    TRANSITION_CSM_PAST_UNWIND_AMT,
    TRANSITION_INPUT_CSM_AMT,
    TRANSITION_INPUT_LC_BE_AMT,
    TRANSITION_INPUT_LC_RA_AMT,
    TRANSITION_LC_BE_PAST_UNWIND_AMT,
    TRANSITION_LC_RA_PAST_UNWIND_AMT,
    FIELD_SOURCE,
    IS_SUBSTANTIAL,
    IS_CHN_COV
FROM stg_object
ORDER BY INSURANCE_CONTRACT_ID, ENDORSEMENT_DT, IS_SUBSTANTIAL
